name: Update Market Data Daily

on:
  schedule:
    - cron: "0 3 * * 2-6" # UTC 3:00 (Beijing 11:00), only Tuesday to Saturday
  workflow_dispatch: # 允许手动触发

jobs:
  update-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 需要写入权限来提交更改

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Run update script
        run: python src/main.py

      - name: Commit and push if there are changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add data/
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            echo "Changes detected in data directory"
            git status
            git commit -m "chore: update market data [skip ci] ($(date +'%Y-%m-%d'))"
            git push origin HEAD
          fi
